/**
 * DigitalBurj Academy public content.
 *
 * Tracks mirror the technology curriculum areas in the Academy specification (DB-00 to DB-22).
 * Course codes, module lists, durations and prices are NOT published here until they are
 * confirmed from the live Academy catalogue (see CONTENT_TODO.md).
 */

export type Track = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  forWho: string;
  skills: string[];
  missions: string[];
};

export const tracks: Track[] = [
  { slug: "digital-foundations", title: "Digital Foundations", category: "technology", summary: "The working knowledge every technology career builds on: how the web, files, data and software tools actually work.", forWho: "Beginners and career changers who need confident, practical digital skills before specialising.", skills: ["How the internet and the web work", "Files, formats and version control basics", "Working in the command line", "Using business software productively", "Safe use of AI tools", "Structured problem solving"], missions: ["Set up a professional development environment", "Diagnose why a website is not loading", "Organise and version a small project"] },
  { slug: "product-thinking", title: "Product Thinking", category: "business", summary: "How to understand users, define problems and decide what is worth building before any code is written.", forWho: "Developers, designers, founders and operators who want to build things people use.", skills: ["Problem framing", "User research basics", "Defining the core action", "Writing requirements", "Prioritisation", "Measuring outcomes"], missions: ["Interview users and write a problem statement", "Scope a first version with a no-build list", "Define success measures for a feature"] },
  { slug: "web-development", title: "Web Development", category: "software-development", summary: "Building accessible, responsive web interfaces with HTML, CSS, JavaScript and a modern framework.", forWho: "Learners aiming for frontend or full-stack roles.", skills: ["Semantic HTML and accessibility", "Responsive CSS layout", "JavaScript fundamentals", "Component-based frameworks", "Forms and validation", "Performance basics"], missions: ["Build an accessible multi-page site", "Implement a validated form with clear errors", "Fix performance and accessibility issues in a broken page"] },
  { slug: "backend-development", title: "Backend Development", category: "software-development", summary: "Designing and building server-side applications, APIs and databases that are correct, secure and maintainable.", forWho: "Learners aiming for backend or full-stack roles.", skills: ["HTTP and API design", "Relational data modelling and SQL", "Authentication and authorisation", "Input validation and error handling", "Transactions and data integrity", "Testing server code"], missions: ["Design and build a documented REST API", "Enforce role-based permissions on the server", "Find and fix a data-integrity bug"] },
  { slug: "ai-engineering", title: "AI Engineering", category: "artificial-intelligence", summary: "Building software features with language models: prompting, retrieval, tool use, evaluation and cost control.", forWho: "Developers who want to build reliable AI features.", skills: ["Working with model APIs", "Prompt and output design", "Retrieval over your own data", "Tool use and structured outputs", "Evaluation sets", "Cost, latency and safety controls"], missions: ["Build a question-answering feature over documents", "Create an evaluation set and measure quality", "Add guardrails and human review to an AI workflow"] },
  { slug: "data-and-analytics", title: "Data & Analytics", category: "data", summary: "Collecting, cleaning, analysing and presenting data so that it supports real decisions.", forWho: "Analysts, operators and developers who work with business data.", skills: ["Spreadsheet analysis", "SQL for analysis", "Data cleaning", "Defining metrics", "Visualisation", "Communicating findings"], missions: ["Clean a messy operational dataset", "Define and calculate a set of business metrics", "Present findings with clear charts"] },
  { slug: "production-engineering", title: "Production Engineering", category: "software-development", summary: "Running software reliably: deployment, monitoring, incidents, backups and recovery.", forWho: "Developers moving from building features to running systems.", skills: ["Deployment pipelines", "Environments and configuration", "Logging and monitoring", "Incident response", "Backups and restores", "Capacity basics"], missions: ["Deploy an application with an automated pipeline", "Add monitoring and alerts", "Restore a system from backup"] },
  { slug: "cybersecurity", title: "Cybersecurity", category: "cybersecurity", summary: "Practical security for people who build and operate software and business systems.", forWho: "Developers, IT staff and operators responsible for systems and data.", skills: ["Threat modelling", "Common web vulnerabilities", "Secure authentication", "Access control", "Secrets management", "Security monitoring"], missions: ["Threat-model a small application", "Find and fix vulnerabilities in a deliberately insecure app", "Review access permissions for a business system"] },
  { slug: "software-testing", title: "Software Testing", category: "software-development", summary: "Designing tests that catch real problems, from unit tests to end-to-end checks.", forWho: "Developers and QA professionals.", skills: ["Test design", "Unit and integration testing", "End-to-end testing", "Testing edge cases", "Accessibility testing", "Writing useful bug reports"], missions: ["Add tests to untested code before changing it", "Write end-to-end tests for a critical journey", "Report and reproduce a subtle bug"] },
  { slug: "payments", title: "Payments", category: "software-development", summary: "Building payment flows that handle money correctly: providers, webhooks, reconciliation and failure.", forWho: "Developers building commerce, SaaS or marketplace products.", skills: ["Payment provider integration", "Webhooks and idempotency", "Subscriptions", "Refunds and disputes", "Reconciliation", "Security requirements"], missions: ["Integrate a test payment provider", "Handle duplicate webhook delivery safely", "Reconcile payments against orders"] },
  { slug: "real-time-systems", title: "Real-Time Systems", category: "software-development", summary: "Building features that update live: messaging, notifications, collaboration and tracking.", forWho: "Developers building interactive and collaborative products.", skills: ["WebSockets and server-sent events", "Presence and live updates", "Message ordering", "Offline and reconnection", "Scaling connections", "Testing real-time features"], missions: ["Build a live status tracker", "Handle reconnection without losing updates"] },
  { slug: "document-systems", title: "Document Systems", category: "software-development", summary: "Building systems that store, process, generate and secure business documents.", forWho: "Developers building document-heavy business software.", skills: ["Private file storage", "Access-controlled downloads", "Document generation", "Data extraction", "Versioning and audit", "Retention"], missions: ["Build private document upload with authorised access", "Generate documents from templates", "Extract and validate fields from uploaded files"] },
  { slug: "ai-agents-and-automation", title: "AI Agents & Automation", category: "artificial-intelligence", summary: "Designing bounded automations and AI agents with permissions, approvals and logging.", forWho: "Developers and operations professionals automating business workflows.", skills: ["Workflow design", "Integration platforms and APIs", "Agent tool design", "Human approval steps", "Logging and review", "Measuring automation results"], missions: ["Automate an enquiry workflow end to end", "Build an agent with a narrow tool set and approval step", "Measure an automation against its baseline"] },
  { slug: "business-systems", title: "Business Systems", category: "business", summary: "Understanding and configuring the systems businesses run on: CRM, ERP, accounting and workflow tools.", forWho: "Operations staff, analysts and developers working with business software.", skills: ["CRM concepts and configuration", "ERP and accounting basics", "System-of-record thinking", "Integration patterns", "Data quality", "User adoption"], missions: ["Configure a CRM pipeline for a scenario", "Map data flow across three business systems"] },
  { slug: "mobile-development", title: "Mobile Development", category: "software-development", summary: "Building mobile applications that are usable, accessible and reliable on real devices.", forWho: "Developers targeting iOS and Android.", skills: ["Mobile UI patterns", "Cross-platform frameworks", "Device features", "Offline storage", "Push notifications", "Release management"], missions: ["Build a mobile client for an existing API", "Handle offline use and sync"] },
  { slug: "search-and-visibility", title: "Search & Visibility", category: "business", summary: "Making websites and content discoverable by search engines and AI systems through structure and quality.", forWho: "Developers, marketers and content owners.", skills: ["Technical SEO", "Structured data", "Content structure for answers", "Performance and Core Web Vitals", "Measuring search performance", "Accessibility and semantics"], missions: ["Audit and fix technical SEO on a site", "Add valid structured data", "Rewrite a page to answer questions directly"] },
  { slug: "product-development", title: "Product Development", category: "business", summary: "Taking a product from validated idea to launched, measured software.", forWho: "Founders, product managers and developers.", skills: ["Validation", "MVP scoping", "Roadmapping", "Working with engineering", "Launch planning", "Product analytics"], missions: ["Validate a product idea with evidence", "Plan and ship a scoped first release"] },
  { slug: "digital-transformation", title: "Digital Transformation", category: "business", summary: "Changing how organisations operate with process redesign, systems and automation.", forWho: "Managers and operators leading change.", skills: ["Process mapping", "Finding operational leaks", "Baselines and measurement", "Change management", "Vendor and system selection", "Automation governance"], missions: ["Map a process and identify where work is lost", "Build a baseline and improvement plan"] },
  { slug: "freelancing", title: "Freelancing", category: "business", summary: "Working independently with clients: scoping, pricing, delivery and professional conduct.", forWho: "Professionals building independent client work.", skills: ["Scoping work", "Proposals and pricing", "Client communication", "Contracts basics", "Delivery and handover", "Building a portfolio"], missions: ["Write a proposal from a client brief", "Handle a scope-change request professionally"] },
  { slug: "professional-practice", title: "Professional Practice", category: "business", summary: "The habits that make someone reliable at work: communication, documentation, estimation and accountability.", forWho: "Anyone moving into professional technology work.", skills: ["Written communication", "Documentation", "Estimation", "Code and work review", "Working in teams", "Ethics and responsibility"], missions: ["Document a system for a new team member", "Explain and defend a technical decision"] },
];

export type AcademyCategory = {
  slug: string;
  title: string;
  h1: string;
  group: "technology" | "professional";
  description: string;
  answer: string;
  whatTheyDo: string[];
  skills: string[];
  forWho: string[];
  roles: string[];
  /** Track slugs mapped to this category. */
  trackCategory?: string[];
  path?: string;
  /** Professional categories stay out of the index until courses are published. */
  indexable: boolean;
};

export const academyCategories: AcademyCategory[] = [
  { slug: "technology", title: "Technology", h1: "Technology Courses & Career Learning", group: "technology", description: "Practical technology learning at DigitalBurj Academy: software, AI, data, cybersecurity and production engineering, built around projects and evidence.", answer: "DigitalBurj Academy technology learning covers software development, artificial intelligence, data and cybersecurity. Every track is practical: learners build, break, fix and explain real work, and finish with evidence of what they can do rather than only a completion certificate.", whatTheyDo: ["Build and maintain software products", "Design data systems and analyses", "Secure applications and infrastructure", "Build AI features and automations"], skills: ["Programming and problem solving", "Working with data", "Security awareness", "Testing and quality", "Communication and documentation"], forWho: ["Career starters", "Career changers", "Working professionals upskilling", "Teams adopting new technology"], roles: ["Web developer", "Backend developer", "Data analyst", "AI engineer", "QA engineer", "Security analyst"], trackCategory: ["technology", "software-development", "artificial-intelligence", "data", "cybersecurity"], path: "software-developer", indexable: true },
  { slug: "artificial-intelligence", title: "Artificial Intelligence", h1: "Artificial Intelligence Courses", group: "technology", description: "Learn to build AI features and automations that work reliably: language models, retrieval, agents, evaluation and responsible use.", answer: "DigitalBurj Academy AI learning teaches how to build useful, controlled AI features: working with language models, grounding them in real data, giving them tools, evaluating their quality and keeping humans in the loop. The focus is engineering reliable systems, not prompting tricks.", whatTheyDo: ["Build AI-powered product features", "Automate business workflows with AI", "Evaluate and monitor AI quality", "Advise on safe AI use"], skills: ["Model APIs and prompting", "Retrieval and data grounding", "Agent and tool design", "Evaluation", "Security and privacy", "Cost control"], forWho: ["Developers adding AI to products", "Automation and operations specialists", "Technical product managers"], roles: ["AI engineer", "Automation developer", "AI product developer"], trackCategory: ["artificial-intelligence"], path: "ai-developer", indexable: true },
  { slug: "software-development", title: "Software Development", h1: "Software Development Courses", group: "technology", description: "Web, backend, mobile, testing, payments and production engineering tracks at DigitalBurj Academy, taught through practical missions.", answer: "DigitalBurj Academy software development learning takes learners from building interfaces and APIs to testing, deploying and running production systems. Learners work on realistic missions, including debugging broken systems, and must explain and defend their technical decisions.", whatTheyDo: ["Build web and mobile applications", "Design APIs and databases", "Test and deploy software", "Maintain systems in production"], skills: ["Frontend and backend development", "Data modelling", "Authorisation and security", "Testing", "Deployment and monitoring"], forWho: ["Aspiring developers", "Junior developers filling gaps", "Career changers with some coding"], roles: ["Frontend developer", "Backend developer", "Full-stack developer", "Mobile developer"], trackCategory: ["software-development"], path: "software-developer", indexable: true },
  { slug: "data", title: "Data", h1: "Data & Analytics Courses", group: "technology", description: "Learn to clean, analyse, define metrics and present data that supports decisions, at DigitalBurj Academy.", answer: "DigitalBurj Academy data learning teaches how to turn raw operational data into reliable metrics and clear decisions: cleaning data, querying with SQL, defining metrics precisely and presenting findings. Learners work with realistic, messy datasets.", whatTheyDo: ["Prepare and clean data", "Analyse performance", "Build reports and dashboards", "Support decisions with evidence"], skills: ["Spreadsheets", "SQL", "Data cleaning", "Metric definition", "Visualisation"], forWho: ["Aspiring analysts", "Operations and finance staff", "Managers who rely on data"], roles: ["Data analyst", "Reporting analyst", "Operations analyst"], trackCategory: ["data"], indexable: true },
  { slug: "cybersecurity", title: "Cybersecurity", h1: "Cybersecurity Courses", group: "technology", description: "Practical cybersecurity for developers and operators: threat modelling, vulnerabilities, access control and monitoring.", answer: "DigitalBurj Academy cybersecurity learning is practical and builder-focused: how systems are attacked, how to design and review them securely, and how to detect problems. Learners find and fix vulnerabilities in deliberately insecure applications.", whatTheyDo: ["Identify and fix vulnerabilities", "Design secure access", "Monitor for incidents", "Advise teams on secure practice"], skills: ["Threat modelling", "Web security", "Authentication", "Access control", "Monitoring"], forWho: ["Developers", "IT and operations staff", "Aspiring security analysts"], roles: ["Security-aware developer", "Security analyst", "IT administrator"], trackCategory: ["cybersecurity"], indexable: true },
  { slug: "business", title: "Business", h1: "Business, Product & Transformation Learning", group: "technology", description: "Product thinking, business systems, digital transformation, freelancing and professional practice at DigitalBurj Academy.", answer: "DigitalBurj Academy business learning connects technology with how organisations work: understanding users and problems, configuring business systems, leading digital change and working professionally with clients and teams.", whatTheyDo: ["Define products and requirements", "Configure and improve business systems", "Lead process change", "Work with clients"], skills: ["Product thinking", "Business systems", "Process mapping", "Communication", "Professional practice"], forWho: ["Operators and managers", "Product and project roles", "Freelancers"], roles: ["Product owner", "Business systems analyst", "Transformation lead", "Freelance consultant"], trackCategory: ["business"], path: "business-automation", indexable: true },
  { slug: "accounting-finance", title: "Accounting & Finance", h1: "Accounting & Finance Career Learning", group: "professional", description: "Career learning for accounting and finance roles: bookkeeping, reporting, systems and controls. Courses in preparation at DigitalBurj Academy.", answer: "Accounting and finance professionals record transactions, prepare reports, manage payables and receivables and maintain financial controls. DigitalBurj Academy is preparing practical learning in this area focused on real tasks, business systems and evidence.", whatTheyDo: ["Record and reconcile transactions", "Manage payables and receivables", "Prepare financial reports", "Support audits and controls"], skills: ["Bookkeeping principles", "Accounting software", "Spreadsheets", "Reconciliation", "Attention to detail", "Reporting"], forWho: ["Career starters in finance", "Administrative staff moving into finance"], roles: ["Accounts assistant", "Bookkeeper", "Accounts payable/receivable clerk"], path: "accounting-professional", indexable: false },
  { slug: "office-administration", title: "Office Administration", h1: "Office Administration Career Learning", group: "professional", description: "Career learning for office administration: coordination, documents, business software and communication. Courses in preparation.", answer: "Office administrators keep organisations running: coordinating schedules, managing documents and records, handling communication and using business software. DigitalBurj Academy is preparing practical learning built around these day-to-day tasks.", whatTheyDo: ["Coordinate schedules and meetings", "Manage documents and records", "Handle internal and external communication", "Support teams with business systems"], skills: ["Business software", "Written communication", "Organisation", "Document management", "Basic data handling"], forWho: ["Career starters", "People returning to work"], roles: ["Office administrator", "Administrative assistant", "Office coordinator"], path: "office-administrator", indexable: false },
  { slug: "logistics", title: "Logistics", h1: "Logistics Courses & Career Learning", group: "professional", description: "Career learning for logistics and freight roles: shipment coordination, documentation, systems and customer communication. Courses in preparation.", answer: "Logistics professionals coordinate the movement of goods: booking shipments, preparing documentation, tracking status, communicating with customers and carriers, and resolving exceptions. DigitalBurj Academy is preparing practical logistics learning built around these real tasks.", whatTheyDo: ["Coordinate shipments", "Prepare shipping documentation", "Track and communicate status", "Resolve exceptions and delays"], skills: ["Shipment processes", "Documentation accuracy", "Logistics systems", "Customer communication", "Problem solving"], forWho: ["Career starters in logistics", "Operations staff moving into freight"], roles: ["Logistics coordinator", "Freight forwarding assistant", "Operations executive"], path: "logistics-coordinator", indexable: false },
  { slug: "real-estate", title: "Real Estate", h1: "Real Estate Career Learning", group: "professional", description: "Career learning for real estate roles: client handling, CRM, documentation and follow-up. Courses in preparation.", answer: "Real estate professionals manage enquiries, qualify clients, arrange viewings, handle documentation and maintain relationships. DigitalBurj Academy is preparing practical learning focused on client handling, CRM use and professional process. Local licensing requirements are separate.", whatTheyDo: ["Qualify and manage enquiries", "Arrange viewings", "Handle documentation", "Maintain client relationships in CRM"], skills: ["Client communication", "CRM use", "Documentation", "Negotiation basics", "Follow-up discipline"], forWho: ["Career starters in real estate", "Agents strengthening process"], roles: ["Real estate agent", "Leasing coordinator", "Sales administrator"], indexable: false },
  { slug: "human-resources", title: "Human Resources", h1: "Human Resources Career Learning", group: "professional", description: "Career learning for HR roles: recruitment, onboarding, records and skills-based hiring. Courses in preparation.", answer: "HR professionals support recruitment, onboarding, employee records and people processes. DigitalBurj Academy is preparing practical learning with an emphasis on skills-based hiring and evidence of capability.", whatTheyDo: ["Support recruitment", "Coordinate onboarding", "Maintain employee records", "Support people processes"], skills: ["Recruitment process", "Skills-based assessment", "HR systems", "Confidentiality", "Communication"], forWho: ["Career starters in HR", "Administrators moving into HR"], roles: ["HR assistant", "Recruitment coordinator", "HR administrator"], indexable: false },
  { slug: "sales-marketing", title: "Sales & Marketing", h1: "Sales & Marketing Career Learning", group: "professional", description: "Career learning for sales and marketing roles: CRM, pipeline discipline, content and search visibility. Courses in preparation.", answer: "Sales and marketing professionals generate interest, qualify opportunities and build customer relationships. DigitalBurj Academy is preparing practical learning covering CRM discipline, customer communication, content and search visibility.", whatTheyDo: ["Generate and qualify leads", "Manage a pipeline", "Create content", "Measure campaign results"], skills: ["CRM use", "Customer communication", "Content writing", "Search visibility", "Reporting"], forWho: ["Career starters", "Salespeople adding digital skills"], roles: ["Sales executive", "Marketing coordinator", "Business development representative"], indexable: false },
];

export type LearningPath = {
  slug: string;
  title: string;
  overview: string;
  forWho: string;
  capabilities: string[];
  sequence: string[];
  projects: string[];
  roles: string[];
  indexable: boolean;
};

export const learningPaths: LearningPath[] = [
  { slug: "software-developer", title: "Software Developer", overview: "A route from digital foundations to building, testing and deploying full-stack web applications.", forWho: "Beginners and career changers aiming for junior developer roles.", capabilities: ["Build accessible web interfaces", "Design APIs and databases", "Enforce permissions securely", "Test and deploy applications", "Explain technical decisions"], sequence: ["digital-foundations", "web-development", "backend-development", "software-testing", "production-engineering", "professional-practice"], projects: ["A multi-page accessible website", "A documented REST API with role-based access", "A deployed full-stack application with monitoring"], roles: ["Junior web developer", "Junior backend developer", "Junior full-stack developer"], indexable: true },
  { slug: "ai-developer", title: "AI Developer", overview: "A route for developers who want to build reliable AI features and automations.", forWho: "People with basic programming experience.", capabilities: ["Integrate language models", "Ground AI in real data", "Design agents with bounded tools", "Evaluate AI quality", "Apply privacy and cost controls"], sequence: ["backend-development", "ai-engineering", "ai-agents-and-automation", "software-testing", "cybersecurity"], projects: ["A document question-answering feature with evaluation", "An automated workflow with human approval"], roles: ["Junior AI engineer", "Automation developer"], indexable: true },
  { slug: "business-automation", title: "Business Automation Specialist", overview: "A route for people who want to improve and automate business operations.", forWho: "Operations staff, analysts and technically minded professionals.", capabilities: ["Map processes and find leaks", "Configure business systems", "Build automated workflows", "Measure results against a baseline"], sequence: ["digital-foundations", "business-systems", "digital-transformation", "ai-agents-and-automation", "data-and-analytics"], projects: ["A mapped and measured process", "An automated enquiry workflow"], roles: ["Automation specialist", "Business systems analyst", "Operations analyst"], indexable: true },
  { slug: "logistics-coordinator", title: "Logistics Coordinator", overview: "Capabilities for coordinating shipments, documentation and customer communication.", forWho: "Career starters in logistics.", capabilities: ["Shipment coordination", "Accurate documentation", "Using logistics systems", "Exception handling", "Customer communication"], sequence: ["digital-foundations", "business-systems"], projects: ["Coordinate a simulated shipment end to end", "Resolve a documentation exception"], roles: ["Logistics coordinator", "Operations assistant"], indexable: false },
  { slug: "office-administrator", title: "Office Administrator", overview: "Capabilities for organised, reliable office administration using modern business tools.", forWho: "Career starters and returners.", capabilities: ["Business software", "Document management", "Scheduling and coordination", "Professional communication"], sequence: ["digital-foundations", "professional-practice"], projects: ["Set up a document and scheduling system for a team"], roles: ["Office administrator", "Administrative assistant"], indexable: false },
  { slug: "accounting-professional", title: "Accounting Professional", overview: "Capabilities for entry-level accounting and finance work.", forWho: "Career starters in finance.", capabilities: ["Bookkeeping", "Reconciliation", "Accounting software", "Reporting"], sequence: ["digital-foundations", "data-and-analytics"], projects: ["Reconcile a month of transactions", "Prepare a simple management report"], roles: ["Accounts assistant", "Bookkeeper"], indexable: false },
];

export const learningLoop = ["Brief", "Learn", "Investigate", "Try", "Build", "Break", "Fix", "Test", "Explain", "Defend", "Ship", "Evidence"];

export function trackBySlug(slug: string) {
  return tracks.find((t) => t.slug === slug);
}
